id = "one-darker"
name = "One Darker"
version = "1.0.0"
schema_version = 1
authors = ["Albert Bogusz"]
description = "Derived from the default One Dark theme, with darker colours and opinionated syntax highlighting."
repository = "https://github.com/albertbogusz/one-darker"